app/frontends/web/config/routes.rb
Web::Application.routes.draw do

  root to: 'pages#index'

  resources :gurus

end

app/frontends/web/app/controllers/application_controller.rb
# -*- coding: UTF-8 -*-

class ApplicationController < ActionController::Base

  protect_from_forgery

  include UseCases

  rescue_from RubyPersistenceAPI::ObjectNotFound, with: :show_404

  private

  def show_404
    render(file: File.join(Rails.root, 'public', '404'), status: 404, :format => :html)
  end

end

app/frontends/web/app/controllers/gurus_controller.rb
# -*- coding: UTF-8 -*-

class GurusController < ApplicationController

  def index
    @rm = ListGurus.new.exec
  end

  def new
    @rm = NewGuru.new.exec
  end

  def create
    @rm = CreateGuru.new(atts: params[:guru]).exec
    @rm.ok? ? redirect_to(gurus_path) : render(:new)
  end

  def show
    @rm = ShowGuru.new(id: params[:id]).exec
  end

  def edit
    @rm = EditGuru.new(id: params[:id]).exec
  end

  def update
    @rm = UpdateGuru.new(id: params[:id], atts: params[:guru]).exec
    @rm.ok? ? redirect_to(gurus_path) : render(:edit)
  end

  def destroy
    @rm = DestroyGuru.new(id: params[:id]).exec
    redirect_to(gurus_path)
  end

end

app/frontends/web/app/controllers/pages_controller.rb
# -*- coding: UTF-8 -*-

class PagesController < ApplicationController

  def index
  end

end

app/frontends/web/app/helpers/application_helper.rb
module ApplicationHelper

  # view model
  def vm
    @vm || @rm # if view model is not set fallback to response model
  end

  def errors(attribute)
    return '' unless vm.errors && !vm.errors.blank?
    content_tag( 'span', class: 'help-inline' ) do
      vm.errors[attribute].join( '; ' )
    end
  end

end

app/frontends/web/app/views/gurus/_form.html.haml
.control-group{ class: ( vm.errors ? 'error' : '' ) }
  %label.control-label{ for: 'guru_name' }
    Name
  .controls
    %input.span5{ type: 'text', id: 'guru_name', name: 'guru[name]', value: vm.guru.name }
    = errors(:name)

.control-group
  %label.control-label{ for: 'guru_homepage' }
    Official site
  .controls
    %input.span5{ type: 'text', id: 'guru_homepage', name: 'guru[homepage]', value: vm.guru.homepage }
    = errors(:homepage)

.control-group
  %label.control-label{ for: 'guru_description' }
    Description
  .controls
    %textarea.span5{ id: 'guru_description', name: 'guru[description]', value: vm.guru.description }
    = errors(:description)

app/frontends/web/app/views/gurus/edit.html.haml
= form_for( vm.guru, as: 'guru', url: guru_path( vm.guru ), :html => { class: 'form-horizontal' } ) do |f|

  %fieldset
    %legend
      = vm.guru.name

    = render 'form', f: f

    .form-actions
      %button{ class: 'btn btn-primary', type: 'submit' }
        Save changes
      %button{ class: 'btn', type: 'button', onclick: 'history.go(-1)' }
        Cancel

app/frontends/web/app/views/gurus/index.html.haml
- @title = 'Known gurus'

.gurus
  - vm.gurus.each do |guru|
    .guru.row{ style: 'padding-top: 8px; padding-bottom: 8px;' }
      .name.span4
        %h4
          = guru.name
        = link_to( guru.homepage, guru.homepage )
      .description.span6
        = guru.description
      .options.span2
        = link_to( "show", guru_path( guru ) )
        = link_to( "edit", edit_guru_path( guru ) )
        = link_to( "delete", guru_path( guru ), :method => :delete )

.options{ style: 'margin-top: 16px;' }
  = link_to( "New guru", new_guru_path, class: 'btn' )

app/frontends/web/app/views/gurus/new.html.haml
= form_for( vm.guru, as: 'guru', url: gurus_path, :html => { class: 'form-horizontal' } ) do |f|

  %fieldset
    %legend
      New Guru

    = render 'form', f: f

    .form-actions
      %button{ class: 'btn btn-primary', type: 'submit' }
        Create
      %button{ class: 'btn', type: 'button', onclick: 'history.go(-1)' }
        Cancel

app/frontends/web/app/views/gurus/show.html.haml
- @title = vm.guru.name

.guru.row
  .name.span4
    %h4
      = vm.guru.name
    = link_to( vm.guru.homepage, vm.guru.homepage )
  .description.span6
    = vm.guru.description
  .options.span2
    = link_to( "edit", edit_guru_path( vm.guru ) )
    = link_to( "delete", guru_path( vm.guru ), :method => :delete )

.options{ style: 'margin-top: 16px;' }
  = link_to( "Back to guru list", gurus_path, class: 'btn' )

app/frontends/web/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= @title || 'GuruWatch.org' %>
  </title>
  <%= stylesheet_link_tag "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class='row'>
      <div class='span12'>
        <h1><%= @title %></h1>

        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/frontends/web/app/views/pages/index.html.haml
- @title = 'Watch the masters at work with GuruWatch'

.teaser
  %p
    There are exceptional individuals who create exceptionally worthwile content.
    In such rare cases you do not want to miss any piece of wisdom they share.
    This site is dedicated to track and link whatever your gurus create.

  %p
    You choose your own gurus. You link their content. The benefit over using a notepad is that
    community will help you watch your guru by adding new resources you may have missed.

  %p
    Content you can track includes conference talks, white papers, books, articles, comments,
    projects and in fact any linkable resource.

.options
  Now, why don't you
  = link_to( 'see the gurus', gurus_path )
  or
  = link_to( 'add your own guru', new_guru_path ) + '?'.html_safe